_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.10
            "6": 4.50.3
            "8":
                - 2
                - 5
            "12": 0.19.10
            "13": linux-x86_64
batch_size:
    value: 32
learning_rate:
    value: 0.0001
num_epochs:
    value: 20
seq_len:
    value: 512
slice_size:
    value: 4
weight_decay:
    value: 2e-05
