alpaca_eval_vllm_llama3_70b_fn:
  prompt_template: "alpaca_eval_vllm_llama3_70b_fn/alpaca_eval_fn.txt"
  fn_completions: "vllm_local_completions"
  completions_kwargs:
    model_name: "/home/shu4/koa_scratch/s2025-assignment3-alignment/Qwen/Qwen2.5-3B-Instruct"
    model_kwargs:
      trust_remote_code: True
      tokenizer_mode: "auto"
      max_model_len: 1000
      tp: 2
    max_new_tokens: 100
    temperature: 0.0
    top_p: 1.0
    batch_size: 900
  fn_completion_parser: "ranking_parser"
